### ISSUE TITLE
Hide status bar and software buttons when screen light is on

### ISSUE THREAD

**Issue by n-o-o-b** [garmax1/material-flashlight#1]
The status bar and sotware buttons are still shown when the screen flashlight is turned on. See below:

![screenshot_20180423-115006](https://user-images.githubusercontent.com/19697175/39122605-58dc9710-46ed-11e8-9589-43a5d9302cd0.png)

Would be better if they were hidden when the flashlight is on.

My device is the Motorola Moto E 2nd Gen 4G, running Android 7.1.2, LineageOS 14.1

**Comment by garmax1** [comment]
Will be done in version 2

**Comment by n-o-o-b** [comment]
Thank you!
