### ISSUE TITLE
App only shows white screen

### ISSUE THREAD

**Issue by n-o-o-b** [garmax1/material-flashlight#10]
If I open the app, I can only see the white screen. I cannot access anything else, the screen with the nice animations is not available. The button to turn the torch off does not work. Android 7.1.2, LineageOS 14.1, Moto E 2nd Gen 4G.

Screenshot:
![screenshot_20180727-104313 1](https://user-images.githubusercontent.com/19697175/43314525-1959d27c-918b-11e8-9991-2e7dc0bd4665.png)

**Comment by garmax1** [comment]
Thank you for your report. Will fix.
