### ISSUE TITLE
Alternative download source

### ISSUE THREAD

**Issue by IzzySoft** [garmax1/material-flashlight#15]
Would you consider making your app available to those outside of Play Store – e.g. by [tagging your releases](https://github.com/garmax1/material-flashlight/releases) and attaching the APK there, or even having it listed at [F-Droid](https://f-droid.org/)?

**Comment by garmax1** [comment]
Hi. Done https://github.com/garmax1/material-flashlight/releases/tag/v2.5

**Comment by IzzySoft** [comment]
Wow, that was fast! May I ask you sign it for v1 as well (i.e. tick both boxes: v1 and v2 signature)? Else `minSdkVersion 16` has not much effect for those on pre-Nougat devices (v2 signatures were introduced with Nougat AFAIR, so older versions rely on v1).

```
$ apksigner verify material-flashlight-2.5.apk |grep -v WARN
DOES NOT VERIFY
ERROR: No JAR signatures
```

(means: no v1 signatures found)

**Comment by garmax1** [comment]
Updated release with v1 sign version

**Comment by garmax1** [comment]
I don't plan release in the future. Just bug fixing and new android version support maybe. I can use both sign version for future releases. F-Droid listing at your discretion. Thank you.

**Comment by IzzySoft** [comment]
Thanks a lot! A single APK signed both v1+v2 is fine (and what I would have suggested). I've just [submitted an RFP](https://gitlab.com/fdroid/rfp/issues/1100) (Request For Packaging) with F-Droid then. Let's see what the scanner there says (other than mine, that one scans the repo – mine scans the DEX).

**Comment by IzzySoft** [comment]
That went well, all fine! Though you might wish to secure your gradlew (see [here](https://gitlab.com/fdroid/rfp/issues/1100#note_217077537)).

**Comment by garmax1** [comment]
Great! Well done. To secure i see that we need to add distributionSha256Sum with apk's hash. Will add.

**Comment by IzzySoft** [comment]
It was you who did well :wink: And yes, please add. Doesn't affect F-Droid though (hence no show-stopper there), but your own builds.
